# Generated by Django 4.2.1 on 2023-06-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('organisations_producteurs', 'ORGANISATIONS DE PRODUCTEURS'), ('agregateur', 'AGREGATEUR'), ('institut_financiere', 'INSTITUT FINANCIERE'), ('Fournisseur_intrants', 'FOURNISSEUR INTRANTS'), ('producteur_individuel', 'PRODUCTEUR INDIVIDUEL'), ('autre', 'AUTRE')], max_length=100)),
                ('prenom_nom', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=100)),
                ('cni', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=12)),
                ('genre', models.CharField(blank=True, choices=[('homme', 'HOMME'), ('femme', 'FEMME')], max_length=100)),
                ('age', models.CharField(blank=True, choices=[('jeune', '[15-29]'), ('adulte', '+30')], max_length=100)),
                ('localisation_parcelle', models.CharField(blank=True, max_length=100)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nom_faitiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefeciaire', to='organisations.faitieres')),
            ],
        ),
    ]
