# Generated by Django 4.2.1 on 2023-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_beneficiaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('pompage', 'KIT DE POMPAGE'), ('semence', 'SEMENCE'), ('engrais_chimique', 'ENGRAIS CHIMIQUE'), ('engrais_organique', 'ENGRAIS ORGANIQUE')], max_length=100)),
            ],
        ),
    ]
