# Generated by Django 4.2.1 on 2023-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_intrants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_entreprise', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
