# Generated by Django 4.2.1 on 2023-06-12 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_bons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bon_livraisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_bl', models.CharField(blank=True, max_length=100)),
                ('reference_facture', models.CharField(blank=True, max_length=100)),
                ('date_livraison', models.DateField(null=True)),
                ('date_installation', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
                ('facture', models.TextField(null=True)),
                ('Bon_livraisons', models.TextField(null=True)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraisons', to='organisations.beneficiaires')),
                ('bon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraisons', to='organisations.bons')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraisons', to='organisations.fournisseurs')),
                ('intrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bon_livraisons', to='organisations.intrants')),
            ],
        ),
    ]
